### PR TITLE
Add high level overview

### PR DESCRIPTION
**Pull request by jhorbulyk**
Add a document where I try to provide a high level overview of all the features of the platform with links to the corresponding documentation.

Flagging @khanzadyan and @drobiazko for review

### CODE REVIEW

**Comment by zubairov** [comment]
Updated reviewers list. What is the deadline?

**Comment by jhorbulyk** [comment]
@drobiazko I created this list because IMO elastic.io is missing a high level description of all the platform concepts and how they fit together in written form.   Where such a description belongs and how such a description is presented is something we can discuss further when we have time.

**Comment by jhorbulyk** [comment]
Make PR changes:
* Change document titles
* Remove Freshdesk links
* Make links relative
* Move documents to reference section
* Add diagrams

**Comment by khanzadyan** [comment]
Will come back to this in a different pull request.

**Pull request closed without merging**
