### PR TITLE
Moved all JSONata example into a single mapping article

### PR DESCRIPTION
**Pull request by drobiazko**

### CODE REVIEW

**Comment by drobiazko** [comment]
Because jumping between pages is a horrible reading experience. It's way easier to navigate using the links in the `Covered in this article` nav on the right side.

**Comment by jhorbulyk** [comment]
At the very least can we have varying levels of indentation?

**Comment by drobiazko** [comment]
We can but at the moment the logic for the nav on the side is a bit inflexible. We need to redesign it a little bit.

**Comment by jhorbulyk** [comment]
Does the design break when using differing levels of headers?

**Comment by khanzadyan** [comment]
> Does the design break when using differing levels of headers?

@jhorbulyk at the moment design takes only H2 level headers and displays them as a page navigation on the right side.

**Comment by drobiazko** [comment]
So @jhorbulyk do you want to block this pr?

**Comment by jhorbulyk** [comment]
If changing some H2 to H3 results in loss of page navigation on the right side then this PR can be merged as is, but I would like to see a link between this issue and the re-design issue so this information is not lost in the future.  If H3 headers are rendered the same as H2 headers, then we should change to H3 headers in this PR so that we don't loose track of this information in the future.

**Pull request merged**
