### PR TITLE
Allow components files to be grouped into sub-folders

### PR DESCRIPTION
**Pull request by drobiazko**
See as example `jdbc` sub-folder

### CODE REVIEW

**Comment by khanzadyan** [comment]
@drobiazko OK, just checked. It is kind of strange. If I add an article in the folder it would still show in the main article list.
elastic io Documentation 2019-04-03 16-39-04

**Comment by drobiazko** [comment]
@khanzadyan provided update. Please pull and check.

**Comment by khanzadyan** [comment]
@drobiazko great, now it is not showing on the main page. But there are some minor issues still present:
elastic io Documentation 2019-04-04 12-35-08

**Comment by drobiazko** [comment]
I think we can merge it for now because you could link the pages from the index page already today. The improvement in the nav can be done in a separate pr.

**Comment by khanzadyan** [comment]
OK, let's do that then.

**Pull request merged**
